### ISSUE TITLE
Quick.YAML hibrid array makes empty lines?

### ISSUE THREAD

**Issue by latdev** [exilon/QuickLib#130]
Something whong with TYamlArray when TYamlObject with TYamlString inside.

```pascal
    procedure TfmMain.FormCreate(Sender: TObject);
    begin
        var doc := TYamlObject.Create;
        try
            doc.AddPair('String', 'Value1');
            doc.AddPair('Integer', TYamlInteger.Create(38));
            var arr1 := TYamlArray.Create;
                arr1.AddElement(TYamlString.Create('String1'));
                arr1.AddElement(TYamlString.Create('String2'));
                var arrObj1 := TYamlObject.Create;
                    arrObj1.AddPair('ArrObj1String1', 'more');
                    arrObj1.AddPair('ArrObj1String2', 'AndMore');
                    arr1.AddElement(arrObj1); // add arrObj to array
                doc.AddPair('TheArray', arr1); // add arr to doc
            Memo1.Lines.Text := doc.ToYaml;
        finally
            FreeAndNil(doc);
        end;
    end;
```
Memo1 text now looks like this.
```yaml
String: Value1
Integer: 38
TheArray:


  - ArrObj1String1: more
    ArrObj1String2: AndMore
```
Awaited result is
```yaml
String: Value1
Integer: 38
TheArray:
  - String1
  - String2
  - ArrObj1String1: more
    ArrObj1String2: AndMore
```

**Comment by exilon** [comment]
Your yaml isn't correct. An array must be of same kind of elements. I think you should have to try with something like this:

```yaml
String: Value1
Integer: 38
TheObject:
  TheArray1:
    - String1
    - String2
  TheArray2:
    - Arr2String1: more
    - Arr2String2: AndMore
```
